### ISSUE TITLE
TooManySuits version 1.0.7 is unsupported.

### ISSUE THREAD

**Issue by CallMeVerity** [RT0405/TooManySuitsInWorldButtons#1]
Hello! Creator of TooManySuits here, thanks for making this mod, I do not own a VR headset so I was unable to do it myself.

I have recently updated my mod to fix certain bugs and performance issues, unfortunately this inadvertently outdated your mod.

I believe a fix would be simple:

Your current code is `TooManySuits.PluginLoader.Hooks.SuitPanel.transform` but the issue with that is I changed my asset bundle in the update, meaning I no longer set the SuitPanel gameobjects transform itself to the position of the canvas component inside of it.

Here's what SHOULD solve this issue `TooManySuits.PluginLoader.Hooks.SuitPanel.GetComponentInChildren<Canvas>();` which will get the actual canvas itself, then simple access its transform for the new position.

Sorry for the inconvenience this has caused, I would've made a pull request but even though I think I am right in that this will fix the issue, I do not have a VR headset to actually test my theory.

**Comment by RT0405** [comment]
Hello Verity. Thank you for notifying me of this change.
I have updated the mod accordingly.

on another note, you mentioned you did a performance update, so I took a look at your code and found some more room for improvement:

```cs
Hooks.SuitPanel.GetComponentInChildren<Canvas>().renderMode = RenderMode.WorldSpace;
Hooks.SuitPanel.GetComponentInChildren<Canvas>().worldCamera = LocalPlayer.localPlayer.gameplayCamera;

Hooks.SuitPanel.GetComponentInChildren<Canvas>().transform.position =
    StartOfRound.Instance.shipBounds.bounds.center - new Vector3(2.8992f, 0.7998f, 2f);
Hooks.SuitPanel.GetComponentInChildren<Canvas>().transform.rotation = Quaternion.Euler(0, 180, 0);
Hooks.SuitPanel.GetComponentInChildren<Canvas>().transform.localScale =
    new Vector3(Plugin.TextScale.Value, Plugin.TextScale.Value, Plugin.TextScale.Value);
```

calling GetComponentInChildren() has overhead, it is recommended to cache returned values like so:

```cs
Canvas suitPanelCanvas = Hooks.SuitPanel.GetComponentInChildren<Canvas>();
suitPanelCanvas = RenderMode.WorldSpace;
suitPanelCanvas.worldCamera = LocalPlayer.localPlayer.gameplayCamera;

suitPanelCanvas.transform.position =
    StartOfRound.Instance.shipBounds.bounds.center - new Vector3(2.8992f, 0.7998f, 2f);
suitPanelCanvas.transform.rotation = Quaternion.Euler(0, 180, 0);
suitPanelCanvas.transform.localScale =
    new Vector3(Plugin.TextScale.Value, Plugin.TextScale.Value, Plugin.TextScale.Value);
```

caching it when you make the suit panel would be best. this kind of caching also improves code readability.

you could also replace the consecutive position and rotation setting of the transform with a call to SetPositionAndRotation() which has better performance.

if you'd like I could add a pull request on your github to implement some of these changes after giving it a more thorough look through.

I am also free to merging my mod into yours, as the buttons have no real tie to VR and also work in normal desktop mode since they are just normal vanilla InteractTriggers.

**Comment by CallMeVerity** [comment]
Hello! I haven't really touched the mod in a while so that's why the code is so horrendous... I only updated to fix certain known bugs and what not, and the performance changes I made were just re-implementing the suit caching which I'd accidentally removed. I appreciate the suggestions you've provided and ill be sure to add that at some point (I have no idea why I was getting the component over and over again... lack of sleep probably).

I do not wish to merge anything as I'm pretty lazy and this mod is no longer a priority of mine.
I appreciate that you put time into making this its super helpful for those with a VR headset.

Thank you!
